<a href="https://colab.research.google.com/github/celwyn002/-Linear-Algebra-58019/blob/main/Practical%20Lab%20Exam%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#1 WY
W = np.array([[1,-3],[2,-2],[3,1]])
print("Vector W is" , W)


Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [11]:
import numpy as np

Y= np.array([[1,2,0],[0,-1,2]])
print("Vector Y is" , Y)



Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [12]:
print(np.dot(W,Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]
